### ISSUE TITLE
Setup fails at setupTravis(), info.ghrepo is undefined

### ISSUE THREAD

**Issue by DJTB** [semantic-release/cli#100]
```bash
? Are you using GitHub Enterprise? No
? What is your npm registry? https://registry.npmjs.org/
? What is your npm username? incendiary
? What is your GitHub username? DJTB
? What CI are you using? Travis CI
ERR! semantic-release TypeError: Cannot read property 'slug' of undefined
ERR! semantic-release     at /home/subrosa/.config/yarn/global/node_modules/semantic-release-cli/dist/lib/travis.js:90:68
ERR! semantic-release     at Generator.next (<anonymous>)
ERR! semantic-release     at step (/home/subrosa/.config/yarn/global/node_modules/semantic-release-cli/dist/lib/travis.js:113:191)
ERR! semantic-release     at /home/subrosa/.config/yarn/global/node_modules/semantic-release-cli/dist/lib/travis.js:113:361
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:103:7)
ERR! semantic-release  TypeError: Cannot read property 'slug' of undefined
ERR! semantic-release     at /home/subrosa/.config/yarn/global/node_modules/semantic-release-cli/dist/lib/travis.js:90:68
ERR! semantic-release     at Generator.next (<anonymous>)
ERR! semantic-release     at step (/home/subrosa/.config/yarn/global/node_modules/semantic-release-cli/dist/lib/travis.js:113:191)
ERR! semantic-release     at /home/subrosa/.config/yarn/global/node_modules/semantic-release-cli/dist/lib/travis.js:113:361
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:103:7)
```

line 90 is 
```js
travis.repoid = _.get((yield promisify(travis.repos(info.ghrepo.slug[0], info.ghrepo.slug[1]).get.bind(travis))()), 'repo.id');
```

package.json
```js
"repository": {
    "type": "git",
    "url": "https://github.com/DJTB/KanaWana/"
  },
```

New access tokens have appeared on both of my npm and github accounts.

If I `console.log(info)` in setupTravis I can see my npm and git usernames, password, access tokens. The github repo url is present too, but there is no key for ghrepo.

I have a travis account and I manually toggled the repo.
![image](https://cloud.githubusercontent.com/assets/5353151/21311946/5cb065cc-c61c-11e6-98d8-c40b6159077d.png)

Any help would be appreciated, keen to use sr-cli!

**Comment by k1r0s** [comment]
I having this issue too :'(

**Comment by kbrandwijk** [comment]
I thought git repository url's ended with .git?
