### ISSUE TITLE
Setup fails with "Could not get repo id"

### ISSUE THREAD

**Issue by abalad** [semantic-release/cli#112]
This error is occurring while performing the installation.
**note: I'm using organizations in GitHub and travis**

`D:\Projetos\Truly-UI>semantic-release-cli init 
? What is your npm registry? https://registry.npmjs.org/
? What is your npm username? temainfo-truly
? What is your npm password? ********
WARN semantic-release keytar is not installed correctly, not saving password
? What is your GitHub username? abalad
? What is your GitHub password? ********
WARN semantic-release keytar is not installed correctly, not saving password
? What CI are you using? Travis CI
ERR! semantic-release Error: Could not get repo id
ERR! semantic-release     at C:\Users\Maicon\AppData\Roaming\npm\node_modules\semantic-release-cli\dist\lib\travis.js:92:31
ERR! semantic-release     at Generator.next (<anonymous>)
ERR! semantic-release     at step (C:\Users\Maicon\AppData\Roaming\npm\node_modules\semantic-release-cli\dist\lib\travis.js:114:191)
ERR! semantic-release     at C:\Users\Maicon\AppData\Roaming\npm\node_modules\semantic-release-cli\dist\lib\travis.js:114:361
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:109:7)
ERR! semantic-release  Error: Could not get repo id
ERR! semantic-release     at C:\Users\Maicon\AppData\Roaming\npm\node_modules\semantic-release-cli\dist\lib\travis.js:92:31
ERR! semantic-release     at Generator.next (<anonymous>)
ERR! semantic-release     at step (C:\Users\Maicon\AppData\Roaming\npm\node_modules\semantic-release-cli\dist\lib\travis.js:114:191)
ERR! semantic-release     at C:\Users\Maicon\AppData\Roaming\npm\node_modules\semantic-release-cli\dist\lib\travis.js:114:361
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:109:7)
`

**Comment by luftywiranda13** [comment]
@abalad already set the repo on GitHub?

**Comment by abalad** [comment]
@luftywiranda13 Yes. At the time of installation for the project data step in GITHUb ..

**Comment by luftywiranda13** [comment]
Could you paste your package.json here?

**Comment by lespinalrivera** [comment]
Exact same problem, I read somewhere that has something to do with keychain setup but I am in Windows.

**Comment by pvdlg** [comment]
See semantic-release/semantic-release#380 for possible solutions
