### ISSUE TITLE
Error: Sorry, we experienced an error.

### ISSUE THREAD

**Issue by ethanneff** [semantic-release/cli#118]
Anyone know why I am getting this error?

```sh
$ semantic-release-cli setup
? What is your npm registry? https://registry.npmjs.org/
? What is your npm username? ethanneff
? What is your GitHub username? ethanneff
? What is your GitHub two-factor authentication code? 567871
? What CI are you using? Travis CI
ERR! semantic-release Error: Sorry, we experienced an error.
ERR! semantic-release     at maybeWrapAsError (/usr/local/lib/node_modules/semantic-release-cli/node_modules/bluebird/js/release/util.js:61:12)
ERR! semantic-release     at /usr/local/lib/node_modules/semantic-release-cli/node_modules/bluebird/js/release/nodeback.js:38:50
ERR! semantic-release     at /usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-ci.js:51:21
ERR! semantic-release     at Request._callback (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-http.js:49:13)
ERR! semantic-release     at Request.self.callback (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:187:22)
ERR! semantic-release     at emitTwo (events.js:125:13)
ERR! semantic-release     at Request.emit (events.js:213:7)
ERR! semantic-release     at Request.<anonymous> (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:1044:10)
ERR! semantic-release     at emitOne (events.js:115:13)
ERR! semantic-release     at Request.emit (events.js:210:7)
ERR! semantic-release     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:965:12)
ERR! semantic-release     at emitNone (events.js:110:20)
ERR! semantic-release     at IncomingMessage.emit (events.js:207:7)
ERR! semantic-release     at endReadableNT (_stream_readable.js:1047:12)
ERR! semantic-release     at _combinedTickCallback (internal/process/next_tick.js:102:11)
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:161:9)
ERR! semantic-release  { Error: Sorry, we experienced an error.
ERR! semantic-release     at maybeWrapAsError (/usr/local/lib/node_modules/semantic-release-cli/node_modules/bluebird/js/release/util.js:61:12)
ERR! semantic-release     at /usr/local/lib/node_modules/semantic-release-cli/node_modules/bluebird/js/release/nodeback.js:38:50
ERR! semantic-release     at /usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-ci.js:51:21
ERR! semantic-release     at Request._callback (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-http.js:49:13)
ERR! semantic-release     at Request.self.callback (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:187:22)
ERR! semantic-release     at emitTwo (events.js:125:13)
ERR! semantic-release     at Request.emit (events.js:213:7)
ERR! semantic-release     at Request.<anonymous> (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:1044:10)
ERR! semantic-release     at emitOne (events.js:115:13)
ERR! semantic-release     at Request.emit (events.js:210:7)
ERR! semantic-release     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:965:12)
ERR! semantic-release     at emitNone (events.js:110:20)
ERR! semantic-release     at IncomingMessage.emit (events.js:207:7)
ERR! semantic-release     at endReadableNT (_stream_readable.js:1047:12)
ERR! semantic-release     at _combinedTickCallback (internal/process/next_tick.js:102:11)
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:161:9)
ERR! semantic-release   cause:
ERR! semantic-release    Error: Sorry, we experienced an error.
ERR! semantic-release        at maybeWrapAsError (/usr/local/lib/node_modules/semantic-release-cli/node_modules/bluebird/js/release/util.js:61:12)
ERR! semantic-release        at /usr/local/lib/node_modules/semantic-release-cli/node_modules/bluebird/js/release/nodeback.js:38:50
ERR! semantic-release        at /usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-ci.js:51:21
ERR! semantic-release        at Request._callback (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-http.js:49:13)
ERR! semantic-release        at Request.self.callback (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:187:22)
ERR! semantic-release        at emitTwo (events.js:125:13)
ERR! semantic-release        at Request.emit (events.js:213:7)
ERR! semantic-release        at Request.<anonymous> (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:1044:10)
ERR! semantic-release        at emitOne (events.js:115:13)
ERR! semantic-release        at Request.emit (events.js:210:7)
ERR! semantic-release        at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:965:12)
ERR! semantic-release        at emitNone (events.js:110:20)
ERR! semantic-release        at IncomingMessage.emit (events.js:207:7)
ERR! semantic-release        at endReadableNT (_stream_readable.js:1047:12)
ERR! semantic-release        at _combinedTickCallback (internal/process/next_tick.js:102:11)
ERR! semantic-release        at process._tickCallback (internal/process/next_tick.js:161:9),
ERR! semantic-release   isOperational: true,
ERR! semantic-release   stack: 'Error: Sorry, we experienced an error.\n    at maybeWrapAsError (/usr/local/lib/node_modules/semantic-release-cli/node_modules/bluebird/js/release/util.js:61:12)\n    at /usr/local/lib/node_modules/semantic-release-cli/node_modules/bluebird/js/release/nodeback.js:38:50\n    at /usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-ci.js:51:21\n    at Request._callback (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-http.js:49:13)\n    at Request.self.callback (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:187:22)\n    at emitTwo (events.js:125:13)\n    at Request.emit (events.js:213:7)\n    at Request.<anonymous> (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:1044:10)\n    at emitOne (events.js:115:13)\n    at Request.emit (events.js:210:7)\n    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:965:12)\n    at emitNone (events.js:110:20)\n    at IncomingMessage.emit (events.js:207:7)\n    at endReadableNT (_stream_readable.js:1047:12)\n    at _combinedTickCallback (internal/process/next_tick.js:102:11)\n    at process._tickCallback (internal/process/next_tick.js:161:9)' }

```

**Comment by ethanneff** [comment]
Closing issues. Was able to work around it. It may have been related to the fact I was trying to do a `semantic-release-cli setup` on a module which was already inited with semantic release. 

Thanks,

**Comment by gmarcos87** [comment]
I have the same issue, how do you work around it?
