### ISSUE TITLE
Setup fails with "Sorry, we experienced an error."

### ISSUE THREAD

**Issue by zeke** [semantic-release/cli#123]
Trying to set this up on a new repo, but encountering an error after selecting Travis...

```
$ semantic-release-cli setup
? What is your npm registry? https://registry.npmjs.org/
? What is your npm username? electron
? What is your GitHub username? electron-bot
? What is your GitHub password? ************************************************************************
? What CI are you using? Travis CI
ERR! semantic-release Error: Sorry, we experienced an error.
ERR! semantic-release 
ERR! semantic-release request_id=058d9579-3cd3-4d40-a53a-d6ca73f60ae6
ERR! semantic-release 
ERR! semantic-release     at maybeWrapAsError (/usr/local/lib/node_modules/semantic-release-cli/node_modules/bluebird/js/release/util.js:61:12)
ERR! semantic-release     at /usr/local/lib/node_modules/semantic-release-cli/node_modules/bluebird/js/release/nodeback.js:38:50
ERR! semantic-release     at /usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-ci.js:51:21
ERR! semantic-release     at Request._callback (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-http.js:49:13)
ERR! semantic-release     at Request.self.callback (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:187:22)
ERR! semantic-release     at emitTwo (events.js:125:13)
ERR! semantic-release     at Request.emit (events.js:213:7)
ERR! semantic-release     at Request.<anonymous> (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:1044:10)
ERR! semantic-release     at emitOne (events.js:115:13)
ERR! semantic-release     at Request.emit (events.js:210:7)
ERR! semantic-release     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:965:12)
ERR! semantic-release     at emitNone (events.js:110:20)
ERR! semantic-release     at IncomingMessage.emit (events.js:207:7)
ERR! semantic-release     at endReadableNT (_stream_readable.js:1059:12)
ERR! semantic-release     at _combinedTickCallback (internal/process/next_tick.js:138:11)
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:180:9)
ERR! semantic-release  { Error: Sorry, we experienced an error.
ERR! semantic-release 
ERR! semantic-release request_id=058d9579-3cd3-4d40-a53a-d6ca73f60ae6
ERR! semantic-release 
ERR! semantic-release     at maybeWrapAsError (/usr/local/lib/node_modules/semantic-release-cli/node_modules/bluebird/js/release/util.js:61:12)
ERR! semantic-release     at /usr/local/lib/node_modules/semantic-release-cli/node_modules/bluebird/js/release/nodeback.js:38:50
ERR! semantic-release     at /usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-ci.js:51:21
ERR! semantic-release     at Request._callback (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-http.js:49:13)
ERR! semantic-release     at Request.self.callback (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:187:22)
ERR! semantic-release     at emitTwo (events.js:125:13)
ERR! semantic-release     at Request.emit (events.js:213:7)
ERR! semantic-release     at Request.<anonymous> (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:1044:10)
ERR! semantic-release     at emitOne (events.js:115:13)
ERR! semantic-release     at Request.emit (events.js:210:7)
ERR! semantic-release     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:965:12)
ERR! semantic-release     at emitNone (events.js:110:20)
ERR! semantic-release     at IncomingMessage.emit (events.js:207:7)
ERR! semantic-release     at endReadableNT (_stream_readable.js:1059:12)
ERR! semantic-release     at _combinedTickCallback (internal/process/next_tick.js:138:11)
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:180:9)
ERR! semantic-release   cause: 
ERR! semantic-release    Error: Sorry, we experienced an error.
ERR! semantic-release    
ERR! semantic-release    request_id=058d9579-3cd3-4d40-a53a-d6ca73f60ae6
ERR! semantic-release    
ERR! semantic-release        at maybeWrapAsError (/usr/local/lib/node_modules/semantic-release-cli/node_modules/bluebird/js/release/util.js:61:12)
ERR! semantic-release        at /usr/local/lib/node_modules/semantic-release-cli/node_modules/bluebird/js/release/nodeback.js:38:50
ERR! semantic-release        at /usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-ci.js:51:21
ERR! semantic-release        at Request._callback (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-http.js:49:13)
ERR! semantic-release        at Request.self.callback (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:187:22)
ERR! semantic-release        at emitTwo (events.js:125:13)
ERR! semantic-release        at Request.emit (events.js:213:7)
ERR! semantic-release        at Request.<anonymous> (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:1044:10)
ERR! semantic-release        at emitOne (events.js:115:13)
ERR! semantic-release        at Request.emit (events.js:210:7)
ERR! semantic-release        at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:965:12)
ERR! semantic-release        at emitNone (events.js:110:20)
ERR! semantic-release        at IncomingMessage.emit (events.js:207:7)
ERR! semantic-release        at endReadableNT (_stream_readable.js:1059:12)
ERR! semantic-release        at _combinedTickCallback (internal/process/next_tick.js:138:11)
ERR! semantic-release        at process._tickCallback (internal/process/next_tick.js:180:9),
ERR! semantic-release   isOperational: true,
ERR! semantic-release   stack: 'Error: Sorry, we experienced an error.\n\nrequest_id=058d9579-3cd3-4d40-a53a-d6ca73f60ae6\n\n    at maybeWrapAsError (/usr/local/lib/node_modules/semantic-release-cli/node_modules/bluebird/js/release/util.js:61:12)\n    at /usr/local/lib/node_modules/semantic-release-cli/node_modules/bluebird/js/release/nodeback.js:38:50\n    at /usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-ci.js:51:21\n    at Request._callback (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-http.js:49:13)\n    at Request.self.callback (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:187:22)\n    at emitTwo (events.js:125:13)\n    at Request.emit (events.js:213:7)\n    at Request.<anonymous> (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:1044:10)\n    at emitOne (events.js:115:13)\n    at Request.emit (events.js:210:7)\n    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:965:12)\n    at emitNone (events.js:110:20)\n    at IncomingMessage.emit (events.js:207:7)\n    at endReadableNT (_stream_readable.js:1059:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)' }
```

Here's more info about my environment:

```
$ semantic-release-cli --version
3.0.3

$ uname -a
Darwin Zekes-MBP 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

$ node -v
v8.4.0
```

cc @gr2m

**Comment by gr2m** [comment]
Hmm looks very much like this error https://github.com/semantic-release/semantic-release/issues/394, let me respond there

**Comment by gr2m** [comment]
Duplicate of #394

**Comment by gr2m** [comment]
lol I created an issue about this myself a while ago:
https://github.com/semantic-release/cli/issues/47

I hope to catch up with semantic-release things soon :)

**Comment by zeke** [comment]
> creating a Hook requires admin rights.

@gr2m I'm not sure that's the same issue. I'm using a privileged GitHub user.

**Comment by gr2m** [comment]
ohhh ok, hmmm. Can oyu try to make that github user an owner and try again?

**Comment by zeke** [comment]
@gr2m you were right it was the user.

I already have it set up with @zeke but would prefer to use @electron-bot now that it has admin permission to the repo. Should I be able to just run `semantic-release-cli setup` in the project directory again? Tried that but I'm still getting an error.

**Comment by gr2m** [comment]
I’ll need to reproduce the issue. I’ll do the following steps

1. create a new organization with a repository
2. invite a 2nd user, give the user admin rights
3. make sure the user as admin rights on the repository (@zeke maybe double check that in your setup?)
4. run semantic-release on that repository

If you could run through that, maybe invitem myself as the 2nd user, that’d be helpful :)

**Comment by gr2m** [comment]
I was just able to reproduce the error. Even when making my bot account an org owner, I still get the error. I'm looking into it

**Comment by gr2m** [comment]
Okay, at least in my case, the problem was that I created a new github user which did not yet login to travis. When logging in to travis for the first time you have to authorize the travis-ci OAuth app. Once I did that, the error went away. 

I'm sure we can provide a better error message in that case. I'll leave the issue open as a reminder

**Comment by zeke** [comment]
> When logging in to travis for the first time you have to authorize the travis-ci OAuth app.

✅ Worked for me. Thanks!
