### ISSUE TITLE
Add option to recreate token

### ISSUE THREAD

**Issue by unional** [semantic-release/cli#186]
My token used by sem-ver for npm seems to be messed up and I want to recreate a new one.

Right now I have to do `--ask-for-passwords` every time.

It would be nice to have `--clear-npm-token` or `--reset-tokens` option.

**Comment by gr2m** [comment]
what happens if you run it without the `--ask-for-passwords` flags? I think it should re-create tokens, too? I’m pretty sure I did that in the past to reset a repository

**Comment by unional** [comment]
Sorry, my original question was not clear because I didn't have a correct understanding of how it works.

What I am looking for is a way to reset the password token saved in the local computer (is it saved in key-chain?).

Right now every time when I try to setup a new repo without `--ask-for-passwords`, I get this:

```sh
> semantic-release-cli setup
? What is your npm registry? https://registry.npmjs.org/
? What is your npm username? unional
ERR! semantic-release Error: Could not login to npm.
ERR! semantic-release     at getNpmToken (/Users/hwong/.nvm/versions/node/v9.4.0/lib/node_modules/semantic-release-cli/src/lib/npm.js:51:21)
ERR! semantic-release     at <anonymous>
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:160:7)
ERR! semantic-release  { Error: Could not login to npm.
ERR! semantic-release     at getNpmToken (/Users/hwong/.nvm/versions/node/v9.4.0/lib/node_modules/semantic-release-cli/src/lib/npm.js:51:21)
ERR! semantic-release     at <anonymous>
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:160:7)
ERR! semantic-release   stack: 'Error: Could not login to npm.\n    at getNpmToken (/Users/hwong/.nvm/versions/node/v9.4.0/lib/node_modules/semantic-release-cli/src/lib/npm.js:51:21)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:160:7)' }
```

If I use `--ask-for-passwords` it will work but does not update the token saved locally.

**Comment by gr2m** [comment]
> is it saved in key-chain?

Yes, I think it would be best to delete it from there directly if you want to reset them

> Error: Could not login to npm

That looks like an issue on npm, see #190
