### ISSUE TITLE
After update: Cannot find module './password-storage'

### ISSUE THREAD

**Issue by Thatkookooguy** [semantic-release/cli#259]
I just updated to cli (which worked before the update) and encountered the following error:
```
semantic-release-cli setup
ERR! semantic-release Error: Cannot find module './password-storage'
ERR! semantic-release     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
ERR! semantic-release     at Function.Module._load (internal/modules/cjs/loader.js:520:25)
ERR! semantic-release     at Module.require (internal/modules/cjs/loader.js:650:17)
ERR! semantic-release     at require (internal/modules/cjs/helpers.js:20:18)
ERR! semantic-release     at Object.<anonymous> (/Users/nkalman/.nvm/versions/node/v10.3.0/lib/node_modules/semantic-release-cli/src/lib/npm.js:7:25)
ERR! semantic-release     at Module._compile (internal/modules/cjs/loader.js:702:30)
ERR! semantic-release     at loader (/Users/nkalman/.nvm/versions/node/v10.3.0/lib/node_modules/semantic-release-cli/node_modules/babel-register/lib/node.js:144:5)
ERR! semantic-release     at Object.require.extensions.(anonymous function) [as .js] (/Users/nkalman/.nvm/versions/node/v10.3.0/lib/node_modules/semantic-release-cli/node_modules/babel-register/lib/node.js:154:7)
ERR! semantic-release     at Module.load (internal/modules/cjs/loader.js:612:32)
ERR! semantic-release     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
ERR! semantic-release     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
ERR! semantic-release     at Module.require (internal/modules/cjs/loader.js:650:17)
ERR! semantic-release     at require (internal/modules/cjs/helpers.js:20:18)
ERR! semantic-release     at module.exports (/Users/nkalman/.nvm/versions/node/v10.3.0/lib/node_modules/semantic-release-cli/src/index.js:84:11)
ERR! semantic-release  { Error: Cannot find module './password-storage'
ERR! semantic-release     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
ERR! semantic-release     at Function.Module._load (internal/modules/cjs/loader.js:520:25)
ERR! semantic-release     at Module.require (internal/modules/cjs/loader.js:650:17)
ERR! semantic-release     at require (internal/modules/cjs/helpers.js:20:18)
ERR! semantic-release     at Object.<anonymous> (/Users/nkalman/.nvm/versions/node/v10.3.0/lib/node_modules/semantic-release-cli/src/lib/npm.js:7:25)
ERR! semantic-release     at Module._compile (internal/modules/cjs/loader.js:702:30)
ERR! semantic-release     at loader (/Users/nkalman/.nvm/versions/node/v10.3.0/lib/node_modules/semantic-release-cli/node_modules/babel-register/lib/node.js:144:5)
ERR! semantic-release     at Object.require.extensions.(anonymous function) [as .js] (/Users/nkalman/.nvm/versions/node/v10.3.0/lib/node_modules/semantic-release-cli/node_modules/babel-register/lib/node.js:154:7)
ERR! semantic-release     at Module.load (internal/modules/cjs/loader.js:612:32)
ERR! semantic-release     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
ERR! semantic-release     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
ERR! semantic-release     at Module.require (internal/modules/cjs/loader.js:650:17)
ERR! semantic-release     at require (internal/modules/cjs/helpers.js:20:18)
ERR! semantic-release     at module.exports (/Users/nkalman/.nvm/versions/node/v10.3.0/lib/node_modules/semantic-release-cli/src/index.js:84:11)
ERR! semantic-release   stack:
ERR! semantic-release    'Error: Cannot find module \'./password-storage\'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:520:25)\n    at Module.require (internal/modules/cjs/loader.js:650:17)\n    at require (internal/modules/cjs/helpers.js:20:18)\n    at Object.<anonymous> (/Users/nkalman/.nvm/versions/node/v10.3.0/lib/node_modules/semantic-release-cli/src/lib/npm.js:7:25)\n    at Module._compile (internal/modules/cjs/loader.js:702:30)\n    at loader (/Users/nkalman/.nvm/versions/node/v10.3.0/lib/node_modules/semantic-release-cli/node_modules/babel-register/lib/node.js:144:5)\n    at Object.require.extensions.(anonymous function) [as .js] (/Users/nkalman/.nvm/versions/node/v10.3.0/lib/node_modules/semantic-release-cli/node_modules/babel-register/lib/node.js:154:7)\n    at Module.load (internal/modules/cjs/loader.js:612:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:543:3)\n    at Module.require (internal/modules/cjs/loader.js:650:17)\n    at require (internal/modules/cjs/helpers.js:20:18)\n    at module.exports (/Users/nkalman/.nvm/versions/node/v10.3.0/lib/node_modules/semantic-release-cli/src/index.js:84:11)',
ERR! semantic-release   code: 'MODULE_NOT_FOUND' }
```

**command ran to update:** `npm i -g semantic-release-cli`
**previous version:** `4.0.9`
**new version:** `4.0.12`
**OS:** MacOS High Sierra
**Node version:** `v10.3.0`
**npm version:** `6.1.0`

**Comment by gr2m** [comment]
Hmm we removed the password storage via #257, there is `require('./password-storage')` in the code any longer. But I was able to reproduce the issue, I’ll have another look

**Comment by pvdlg** [comment]
I just installed the new version and I cannot reproduce. Maybe it's a cache issue somewhere. Try to uninstall/re-install the package.

**Comment by gr2m** [comment]
Yeah when I install semantic-release-cli as a devDependency to just test it locally, I cannot reproduce it. I tried uninstall and re-install, but no luck, I still run into the problem. I also think it’s a caching issue, but not sure how ¯\\_(ツ)\_/¯

**Comment by papakai** [comment]
I am also having this trouble ...

**Comment by WebMatrixware** [comment]
Same issue, currently using npx workaround.

*semantic-release-cli* 4.1.0
*node* 10.15.1
*npm* 6.8.0

**Comment by gr2m** [comment]
@WebMatrixware could you test with latest node / npm versions?

**Comment by Thatkookooguy** [comment]
@gr2m sure. I'll try it later today

Basically since then I moved to installing the cli in the dev dependencies and running it with `npx` for the first time. I like this pattern since it at least gives me a clue that a repo was initialized using the cli and not by copy pasting the `release` section in the package.json

But I'll try it using a global installation later :-)

**Comment by timbergus** [comment]
Same error here. I have installed __semantic-release-cli@4.1.1__ globally following the [getting started](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/getting-started.md#getting-started) instructions, and it throws the error when running `semantic-release-cli setup`.

![Screenshot 2019-04-08 11 13 55](https://user-images.githubusercontent.com/1750734/55712654-6cdd2980-59ef-11e9-9447-56dd40ea8626.png)

This is my environment:

- **semantic-release** version: 4.1.1
- **node version** version: 11.13.0
- **npm version** version: 6.9.0
- **yarn version** version: 1.15.2
