### ISSUE TITLE
ERR! semantic-release Error following repo on CircleCI!

### ISSUE THREAD

**Issue by renanbronchart** [semantic-release/cli#260]
I perform semantic-release-cli, but after all steps, 
I have an error :

ERR! semantic-release Error following repo on CircleCI!

Please, I need some help

**Comment by Leko** [comment]
I try to add error log to `src/lib/circle.js:109`
https://github.com/semantic-release/cli/blob/f98c8987a96ff3419a20bece2b3d01d2664164cd/src/lib/circle.js#L109-L112

The error message is

```
{ StatusCodeError: 403 - {"message":"{\"message\":\"API rate limit exceeded for 34.197.216.176. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\",\"documentation_url\":\"https://developer.github.com/v3/#rate-limiting\"}"}
    at new StatusCodeError (/Users/leko/.anyenv/envs/nodenv/versions/8.11.3/lib/node_modules/semantic-release-cli/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Users/leko/.anyenv/envs/nodenv/versions/8.11.3/lib/node_modules/semantic-release-cli/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Users/leko/.anyenv/envs/nodenv/versions/8.11.3/lib/node_modules/semantic-release-cli/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Users/leko/.anyenv/envs/nodenv/versions/8.11.3/lib/node_modules/semantic-release-cli/node_modules/request/request.js:185:22)
    at emitTwo (events.js:131:20)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/leko/.anyenv/envs/nodenv/versions/8.11.3/lib/node_modules/semantic-release-cli/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/leko/.anyenv/envs/nodenv/versions/8.11.3/lib/node_modules/semantic-release-cli/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'StatusCodeError',
  statusCode: 403,
  message: '403 - {"message":"{\\"message\\":\\"API rate limit exceeded for 34.197.216.176. (But here\'s the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\\",\\"documentation_url\\":\\"https://developer.github.com/v3/#rate-limiting\\"}"}',
  error:
    ...
```

Is it my failt? `34.197.216.176` is not my current IP address.
This ip seems like owned by AWS (https://db-ip.com/34.197.216.176).

**Comment by harrysolovay** [comment]
Same problem... anyone know of a solution?

**Comment by developer239** [comment]
+1

**Comment by unional** [comment]
For the time being, you can go old school:
https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#ci-configuration

Hope that helps! 🌷

**Comment by harrysolovay** [comment]
Thanks @unional!

**Comment by callumlocke** [comment]
It would be really helpful if it could print out the tokens when this error occurs (i.e. fall back to the `Other (prints tokens)` option) instead of just `process.exit(1)`. That way I wouldn't have to go through the whole process again.

**Comment by rjchow** [comment]
using the --ask-for-passwords flag prompts for a CircleCI API token which gets around the rate limiting
e.g:

```
npx semantic-release-cli setup --ask-for-passwords
```

I'm not sure why this isn't documented or isn't the default

**Comment by developer239** [comment]
@rjchow Solve the issue. Also if you don't know where to generate Circle CI token then look here: https://circleci.com/account/api

**Comment by kaseymccurdy** [comment]
# HUGE GOTCHA / THE SOLUTION
If anyone is getting stuck with this, it's likely that you're generating a token on the PROJECT itself. What semantic-release is asking for is a `personal` token which can be generated here: https://circleci.com/account/api

**Comment by jamonholmgren** [comment]
@kaseymccurdy Thanks for your guidance there. The problem now seems to be that the semantic-release-cli thinks the token should be a different length.

```
? What is your CircleCI API token? CCIPAT_xxxxxxxxxxxxxxxxxxxxxx_111111x11xx1x11111x111x1xx1x11xx111
fa0ae

>> Invalid token length
```

Any ideas?
