### ISSUE TITLE
install hangs if GitHub user has no write access to repository

### ISSUE THREAD

**Issue by gr2m** [semantic-release/cli#28]
```
$ npm_config_loglevel=verbose semantic-release-cli setup
verb semantic-release Detected git url: https://github.com/eHealthAfrica/kazana-account-app.git
? Is the GitHub repository private? No
? What is your npm registry? https://registry.npmjs.org/
? What is your npm username? ehealthafrica
? What is your npm email? oss@ehealthafrica.org
verb semantic-release adduser before first PUT { _id: 'org.couchdb.user:ehealthafrica',
verb semantic-release   name: 'ehealthafrica',
verb semantic-release   password: 'XXXXX',
verb semantic-release   email: 'oss@ehealthafrica.org',
verb semantic-release   type: 'user',
verb semantic-release   roles: [],
verb semantic-release   date: '2015-09-21T14:54:27.862Z' }
verb semantic-release request uri https://registry.npmjs.org/-/user/org.couchdb.user:ehealthafrica
verb semantic-release request new user, so can't send auth
info semantic-release attempt registry request try #1 at 16:54:27
verb semantic-release request id 1d440b1fa8155f43
http semantic-release request PUT https://registry.npmjs.org/-/user/org.couchdb.user:ehealthafrica
http semantic-release 201 'https://registry.npmjs.org/-/user/org.couchdb.user:ehealthafrica'
info semantic-release Successfully created npm token.
? What is your GitHub username? ehealthafrica-ci
? What is your GitHub password? ************************************************************
```

After giving the GitHub user write-access to the repo, it failed with "Could not load Travis CI config for endpoint"

```
$ npm_config_loglevel=silly semantic-release-cli setup
verb semantic-release Detected git url: https://github.com/eHealthAfrica/kazana-account-app.git
? Is the GitHub repository private? No
? What is your npm registry? https://registry.npmjs.org/
? What is your npm username? ehealthafrica
? What is your npm email? oss@ehealthafrica.org
? What is your npm password? ***************
verb semantic-release adduser before first PUT { _id: 'org.couchdb.user:ehealthafrica',
verb semantic-release   name: 'ehealthafrica',
verb semantic-release   password: 'XXXXX',
verb semantic-release   email: 'oss@ehealthafrica.org',
verb semantic-release   type: 'user',
verb semantic-release   roles: [],
verb semantic-release   date: '2015-09-21T15:08:15.928Z' }
verb semantic-release request uri https://registry.npmjs.org/-/user/org.couchdb.user:ehealthafrica
verb semantic-release request new user, so can't send auth
info semantic-release attempt registry request try #1 at 5:08:15 PM
verb semantic-release request id 2e28a0b3a3b1a08b
http semantic-release request PUT https://registry.npmjs.org/-/user/org.couchdb.user:ehealthafrica
http semantic-release 201 'https://registry.npmjs.org/-/user/org.couchdb.user:ehealthafrica'
info semantic-release Successfully created npm token.
? What is your GitHub username? ehealthafrica-ci
? What is your GitHub password? ************************************************************
info semantic-release Successfully created GitHub token.
? What CI are you using? Travis CI
info semantic-release Could not load Travis CI config for endpoint.
ERR! semantic-release Could not create Travis CI hook.
ERR! semantic-release Error: Travis encountered an error, sorry :(
ERR! semantic-release     at /Users/gregor/.nvm/versions/node/v4.0.0/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-ci.js:49:30
ERR! semantic-release     at Request._callback (/Users/gregor/.nvm/versions/node/v4.0.0/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-http.js:49:13)
ERR! semantic-release     at Request.self.callback (/Users/gregor/.nvm/versions/node/v4.0.0/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/index.js:148:22)
ERR! semantic-release     at emitTwo (events.js:87:13)
ERR! semantic-release     at Request.emit (events.js:172:7)
ERR! semantic-release     at Request.<anonymous> (/Users/gregor/.nvm/versions/node/v4.0.0/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/index.js:886:14)
ERR! semantic-release     at emitOne (events.js:82:20)
ERR! semantic-release     at Request.emit (events.js:169:7)
ERR! semantic-release     at IncomingMessage.<anonymous> (/Users/gregor/.nvm/versions/node/v4.0.0/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/index.js:837:12)
ERR! semantic-release     at emitNone (events.js:72:20)
ERR! semantic-release  [Error: Travis encountered an error, sorry :(]
```

Not sure if that is related, feel free to create a separate issue for the Travis-ci part

**Comment by borismus** [comment]
I'm seeing this too, no idea what the problem is...

**Comment by paralin** [comment]
Any progress on this?

**Comment by uglow** [comment]
I got the same error "Could not load Travis CI config for endpoint.". So I tried logging in to Travis CI with my GitHub account and was redirected to https://api.travis-ci.org/auth/handshake/github?redirect_uri=https://travis-ci.org/, which then said "Forbidden". Not sure what the resolution is yet.
