### ISSUE TITLE
No able to use semantic-release-cli at all

### ISSUE THREAD

**Issue by labdave** [semantic-release/cli#296]
Hello,

I am a newbie in the semantic versioning world. I came to know about the semantic-release and it's goodies while reading some online resources. Recently, I decided to give it a shot.

I follow the installation instructions described in the GitHub repo. The installation works fine but when it comes to setting up for the new project I experienced the error as described below in code block.

Please note, I would like to use `sematic-release-cli`, `semantic-release`, and it's plugins for `non-npm` project.

 
```bash
# System information
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

# NPM version
$ npm --version
6.10.3

# Nodejs version
$ nodejs --version
v10.16.2

# Uniinstall the module
$ sudo npm uninstall -g semantic-release-cli
removed 846 packages in 2.776s

# re-install the module
$ sudo npm install -g semantic-release-cli
npm WARN deprecated github@0.1.16: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)
/usr/bin/semantic-release-cli -> /usr/lib/node_modules/semantic-release-cli/bin/semantic-release.js

> core-js@2.6.9 postinstall /usr/lib/node_modules/semantic-release-cli/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

+ semantic-release-cli@5.1.2
added 846 packages from 929 contributors in 17.584s

# creating test directory
$ mkdir test_module
$ cd test_module

# trying to set up the module
$ semantic-release-cli setup
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open './package.json'
    at Object.openSync (fs.js:443:3)
    at readFileSync (fs.js:343:35)
    at Object.<anonymous> (/usr/lib/node_modules/semantic-release-cli/src/index.js:10:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at loader (/usr/lib/node_modules/semantic-release-cli/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/lib/node_modules/semantic-release-cli/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/lib/node_modules/semantic-release-cli/bin/semantic-release.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

Can some please help me to resolve the issue?

Thank you.

Best,
Tushar

**Comment by gr2m** [comment]
The folder where you run `semantic-release-cli setup`, does it have a package.json?

COuld you try to uninstall it and run it with `npx semantic-release-cli setup`?

**Comment by tushardave26** [comment]
## Uninstall the package

```bash
$ sudo npm -g uninstall semantic-release-cli --save
removed 846 packages in 2.767s
```

## Re-install the package

```bash
$ sudo npm -g install semantic-release-cli
npm WARN deprecated github@0.1.16: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)
/usr/bin/semantic-release-cli -> /usr/lib/node_modules/semantic-release-cli/bin/semantic-release.js

> core-js@2.6.9 postinstall /usr/lib/node_modules/semantic-release-cli/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

+ semantic-release-cli@5.1.2
added 846 packages from 929 contributors in 18.088s
```

## Run the setup command
Setup fails again with following error message
```bash
$ npx semantic-release-cli setup
ENOENT: no such file or directory, open './package.json'
```
Content of the directory that I am running the `setup` command in 
```bash
$ ls -lhrt
total 4.0K
-rw-r--r-- 1 root root 27 Aug 15 15:22 package-lock.json
```

**Comment by gr2m** [comment]
is there a `package.json` file? I only see `package-lock.json`

**Comment by tushardave26** [comment]
No. I created a new directory and went into it and try to run the `setup` command.

```bash
$ mkdir test_project
$ cd test_project
$ npx semantic-release-cli setup
ENOENT: no such file or directory, open './package.json'

$ ls -lhrt
total 4.0K
-rw-r--r-- 1 root root 27 Aug 15 15:22 package-lock.json
```

**Comment by gr2m** [comment]
You need to create a `package.json` and the corresponding repository on GitHub which is referenced in the `package.json` file.

I recommend the `hub` CLI tool to create a repository from your command line:
https://hub.github.com/

Then you can do the following

```shell
mkdir test_project
cd test_project
git init .
hub create
npm init -y
npx semantic-release-cli setup
```

**Comment by tushardave26** [comment]
@gr2m - but my project is not `npm` project. Does `package.json` mandatory to `setup` for the `non-npm` projects?

**Comment by tushardave26** [comment]
Also, is there any way I can avoid `npm` registry steps that `setup` prompt usually ask me to provide input for?

**Comment by gr2m** [comment]
that I don't know, I've only used the CLI for node projects with package.json files myself.

**Comment by tushardave26** [comment]
@gr2m - Ok.

Here is what I have tried so far after what you have suggested:

## Change directory which is already a git repo
```bash
$ cd RNAUtils
```

## Initialize an npm project
```bash
$ npm init -y

=== OUTPUT ===
Wrote to /home/tushar/projects/RNAUtils/package.json:

{
  "name": "RNAUtils",
  "version": "1.0.0",
  "description": "Collection of utilities for RNASeq",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/labdave/RNAUtils.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/labdave/RNAUtils/issues"
  },
  "homepage": "https://github.com/labdave/RNAUtils#readme"
}
```

## Run the setup command
```bash
$ npx semantic-release-cli setup
 What is your npm registry? https://registry.npmjs.org/
? What is your npm username? tushardave26
? What is your npm password? [hidden]
? What is your GitHub username? tushardave26@gmail.com
? What is your GitHub password? [hidden]
? What CI are you using? Travis CI
ERR! semantic-release Sorry, we experienced an error.
ERR! semantic-release 
ERR! semantic-release request_id:f2684dd3-44d4-4274-adaf-82c33187687c
ERR! semantic-release
```

Any idea why am I getting an error on `Travis CI` setup?

Thanks for the help.

**Comment by gr2m** [comment]
Hmm no but I got that recently, too. I'd have to investigate and don't have time right now, sorry.

For the time being, you can log out the tokens and add them as environment variables to travis manually, after enabling the repo in travis

**Comment by tushardave26** [comment]
Thanks. 

I think my conclusion is `semantic-release-cli` is very embedded with the `node` projects. So, I am not going to pursue it for my `non-node` projects.

You can go ahead and close the issue.

Thanks for all your time and efforts.
