### ISSUE TITLE
Enhance error message when setup CLI

### ISSUE THREAD

**Issue by abdelrahmanahmed** [semantic-release/cli#297]
Hi there,

Thanks for providing this package. I just have a comment when I was trying to setup the CLI. I followed your guidelines and I got a confusing error message: 

```
wahdan@linux:~/work/jenkins-sample$ npx semantic-release-cli setup
ERR! semantic-release TypeError: Cannot read property '0' of undefined
ERR! semantic-release     at getRegistry (/home/wahdan/.nvm/versions/node/v8.10.0/lib/node_modules/semantic-release-cli/src/lib/npm.js:59:7)
ERR! semantic-release     at module.exports (/home/wahdan/.nvm/versions/node/v8.10.0/lib/node_modules/semantic-release-cli/src/lib/npm.js:75:16)
ERR! semantic-release     at module.exports (/home/wahdan/.nvm/versions/node/v8.10.0/lib/node_modules/semantic-release-cli/src/index.js:84:11)
ERR! semantic-release     at <anonymous>
ERR! semantic-release  { TypeError: Cannot read property '0' of undefined
ERR! semantic-release     at getRegistry (/home/wahdan/.nvm/versions/node/v8.10.0/lib/node_modules/semantic-release-cli/src/lib/npm.js:59:7)
ERR! semantic-release     at module.exports (/home/wahdan/.nvm/versions/node/v8.10.0/lib/node_modules/semantic-release-cli/src/lib/npm.js:75:16)
ERR! semantic-release     at module.exports (/home/wahdan/.nvm/versions/node/v8.10.0/lib/node_modules/semantic-release-cli/src/index.js:84:11)
ERR! semantic-release     at <anonymous>
ERR! semantic-release   stack: 'TypeError: Cannot read property \'0\' of undefined\n    at getRegistry (/home/wahdan/.nvm/versions/node/v8.10.0/lib/node_modules/semantic-release-c
li/src/lib/npm.js:59:7)\n    at module.exports (/home/wahdan/.nvm/versions/node/v8.10.0/lib/node_modules/semantic-release-cli/src/lib/npm.js:75:16)\n    at module.exports (/home/w
ahdan/.nvm/versions/node/v8.10.0/lib/node_modules/semantic-release-cli/src/index.js:84:11)\n    at <anonymous>' }
```

And I found that my package.json doesn't have the "name" key. after I added the name to my package.json it worked smoothly. I believe the "npm.js" need a better error descriptive.

**Comment by gr2m** [comment]
agreed, pull requests welcome :)

**Comment by abdelrahmanahmed** [comment]
> agreed, pull requests welcome :)

I added this PR ( #298 ) to resolve this.
