### ISSUE TITLE
Set up command fails on Github Enterprise with Self-signed Certificate warning

### ISSUE THREAD

**Issue by KalleV** [semantic-release/cli#303]
Hi,

I'm trying to use the set up command, and it's failing on the Github step with this warning when I am trying to set it up for a Github Enterprise repository:
```
? What is your GitHub password? [hidden]
ERR! semantic-release RequestError: Error: self signed certificate in certificate chain
ERR! semantic-release     at new RequestError (node_modules/semantic-release-cli/node_modules/request-promise-core/lib/errors.js:14:15)
ERR! semantic-release     at Request.plumbing.callback (node_modules/semantic-release-cli/node_modules/request-promise-core/lib/plumbing.js:87:29)
ERR! semantic-release     at Request.RP$callback [as _callback] (node_modules/semantic-release-cli/node_modules/request-promise-core/lib/plumbing.js:46:31)
```

I assume this is because the Github enterprise is using certificates that are not associated with a well known CA since it is an on-premise environment.

Can we add a flag to the CLI to pass to the request for ignoring self-signed certificates?

https://github.com/request/request-promise/issues/225#issuecomment-332292500

**Comment by KalleV** [comment]
This workaround seemed to take care of it: https://github.com/request/request/issues/2061#issuecomment-182573171

**Comment by tma-arf** [comment]
I cannot get past this error after reading provided links, is there a clear indication of how to pass variables like NODE_TLS NODE_TLS_REJECT_UNAUTHORIZED=0 or equivalent to semantic-release, as in v22 he seems to not use them ?
