### ISSUE TITLE
info.github.endpoint is undefined when running npx semantic-release-cli setup

### ISSUE THREAD

**Issue by henrycity** [semantic-release/cli#356]
When running `npx semantic-release-cli setup` with GitHub Actions for my public repository https://github.com/henrycity/movie-browser-frontend, I got this error
```
ERR! semantic-release RequestError: Error: Invalid URI "undefined/repos/henrycity/movie-browser-frontend/actions/secrets/public-key"
ERR! semantic-release     at new RequestError (/Users/tri.tran/.nvm/versions/node/v12.18.3/lib/node_modules/semantic-release-cli/node_modules/request-promise-core/lib/errors.js:14:15)
ERR! semantic-release     at Request.plumbing.callback (/Users/tri.tran/.nvm/versions/node/v12.18.3/lib/node_modules/semantic-release-cli/node_modules/request-promise-core/lib/plumbing.js:87:29)
ERR! semantic-release     at Request.RP$callback [as _callback] (/Users/tri.tran/.nvm/versions/node/v12.18.3/lib/node_modules/semantic-release-cli/node_modules/request-promise-core/lib/plumbing.js:46:31)
ERR! semantic-release     at self.callback (/Users/tri.tran/.nvm/versions/node/v12.18.3/lib/node_modules/semantic-release-cli/node_modules/request/request.js:185:22)
ERR! semantic-release     at Request.emit (events.js:315:20)
ERR! semantic-release     at Request.init (/Users/tri.tran/.nvm/versions/node/v12.18.3/lib/node_modules/semantic-release-cli/node_modules/request/request.js:273:17)
ERR! semantic-release     at Request.RP$initInterceptor [as init] (/Users/tri.tran/.nvm/versions/node/v12.18.3/lib/node_modules/semantic-release-cli/node_modules/request-promise-core/configure/request2.js:45:29)
ERR! semantic-release     at new Request (/Users/tri.tran/.nvm/versions/node/v12.18.3/lib/node_modules/semantic-release-cli/node_modules/request/request.js:127:8)
ERR! semantic-release     at request (/Users/tri.tran/.nvm/versions/node/v12.18.3/lib/node_modules/semantic-release-cli/node_modules/request/index.js:53:10)
ERR! semantic-release     at /Users/tri.tran/.nvm/versions/node/v12.18.3/lib/node_modules/semantic-release-cli/node_modules/request/index.js:100:12
ERR! semantic-release     at createSecret (/Users/tri.tran/.nvm/versions/node/v12.18.3/lib/node_modules/semantic-release-cli/src/lib/github-actions.js:36:28)
ERR! semantic-release     at module.exports (/Users/tri.tran/.nvm/versions/node/v12.18.3/lib/node_modules/semantic-release-cli/src/lib/github-actions.js:83:9)
ERR! semantic-release     at module.exports (/Users/tri.tran/.nvm/versions/node/v12.18.3/lib/node_modules/semantic-release-cli/src/lib/ci.js:50:17)
ERR! semantic-release     at processTicksAndRejections (internal/process/task_queues.js:97:5)
ERR! semantic-release     at module.exports (/Users/tri.tran/.nvm/versions/node/v12.18.3/lib/node_modules/semantic-release-cli/src/index.js:90:5)
```

 I tried to log the `info` object in https://github.com/semantic-release/cli/blob/master/src/lib/ci.js. I notice that `info.github.endpoint` is `undefined`, which causes the error.

```
  giturl: 'https://github.com/henrycity/movie-browser-frontend.git',
  ghrepo: { slug: [ 'henrycity', 'movie-browser-frontend', '' ] },
  npm: {
    registry: 'https://npm.pkg.github.com/',
    authmethod: 'token',
    username: 'henrycity',
    password: 'xxxx,
    token: 'xxxx'
  },
  github: { token: 'xxxx }
```

Version: 5.4.1

**Comment by henrycity** [comment]
Thanks, I think it's working. No more error and I can see that `NPM_TOKEN` is added as a secret in the project setting.
