### ISSUE TITLE
xsel: Can't open display: (null)\n: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by eng-dibo** [semantic-release/cli#362]
I run `npx semantic-release-cli setup` with the following configs
```
? What is your npm registry? https://registry.npmjs.org/
? What is your npm username? eng.dibo
? What is your npm password? [hidden]
? What is your NPM two-factor authentication code? 272088
```
OS: Debian GNU/Linux 10 (buster)

and I installed `sudo apt install xsel`

but I got his error
```
ERR! semantic-release Error: Both xsel and fallback failed
ERR! semantic-release     at makeError (/home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/clipboardy/lib/linux.js:16:11)
ERR! semantic-release     at xselWithFallback (/home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/clipboardy/lib/linux.js:31:10)
ERR! semantic-release     at processTicksAndRejections (internal/process/task_queues.js:94:5)
ERR! semantic-release  Error: Both xsel and fallback failed
ERR! semantic-release     at makeError (/home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/clipboardy/lib/linux.js:16:11)
ERR! semantic-release     at xselWithFallback (/home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/clipboardy/lib/linux.js:31:10)
ERR! semantic-release     at processTicksAndRejections (internal/process/task_queues.js:94:5) {
ERR! semantic-release   stack: 'Error: Both xsel and fallback failed\n' +
ERR! semantic-release     '    at makeError (/home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/clipboardy/lib/linux.js:16:11)\n' +
ERR! semantic-release     '    at xselWithFallback (/home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/clipboardy/lib/linux.js:31:10)\n' +
ERR! semantic-release     '    at processTicksAndRejections (internal/process/task_queues.js:94:5)',
ERR! semantic-release   xselError: Error: Command failed: xsel --clipboard --output
ERR! semantic-release   xsel: Can't open display: (null)
ERR! semantic-release   : Inappropriate ioctl for device
ERR! semantic-release   
ERR! semantic-release   
ERR! semantic-release       at makeError (/home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/execa/index.js:174:9)
ERR! semantic-release       at /home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/execa/index.js:278:16
ERR! semantic-release       at processTicksAndRejections (internal/process/task_queues.js:94:5)
ERR! semantic-release       at xselWithFallback (/home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/clipboardy/lib/linux.js:26:10)
ERR! semantic-release       at Object.default (/home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/semantic-release-cli/src/lib/github.js:25:32) {
ERR! semantic-release     code: 1,
ERR! semantic-release     stdout: '',
ERR! semantic-release     stderr: "xsel: Can't open display: (null)\n: Inappropriate ioctl for device\n",
ERR! semantic-release     failed: true,
ERR! semantic-release     signal: null,
ERR! semantic-release     cmd: 'xsel --clipboard --output',
ERR! semantic-release     timedOut: false,
ERR! semantic-release     killed: false
ERR! semantic-release   },
ERR! semantic-release   fallbackError: Error: Command failed: /home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/clipboardy/fallbacks/linux/xsel --clipboard --output
ERR! semantic-release   /home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/clipboardy/fallbacks/linux/xsel: Can't open display: (null)
ERR! semantic-release   : Inappropriate ioctl for device
ERR! semantic-release   
ERR! semantic-release   
ERR! semantic-release       at makeError (/home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/execa/index.js:174:9)
ERR! semantic-release       at /home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/execa/index.js:278:16
ERR! semantic-release       at processTicksAndRejections (internal/process/task_queues.js:94:5)
ERR! semantic-release       at xselWithFallback (/home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/clipboardy/lib/linux.js:29:11)
ERR! semantic-release       at Object.default (/home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/semantic-release-cli/src/lib/github.js:25:32) {
ERR! semantic-release     code: 1,
ERR! semantic-release     stdout: '',
ERR! semantic-release     stderr: "/home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/clipboardy/fallbacks/linux/xsel: Can't open display: (null)\n" +
ERR! semantic-release       ': Inappropriate ioctl for device\n',
ERR! semantic-release     failed: true,
ERR! semantic-release     signal: null,
ERR! semantic-release     cmd: '/home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/clipboardy/fallbacks/linux/xsel --clipboard --output',
ERR! semantic-release     timedOut: false,
ERR! semantic-release     killed: false
ERR! semantic-release   }
ERR! semantic-release }
```

when I run `xsel --clipboard --output` I got 
```
xsel: Can't open display: (null)
: Success
```

**Comment by gr2m** [comment]
this looks like a problem with [`xsel`](https://www.npmjs.com/package/xsel), not sure why this relates to semantic-release?

**Comment by eng-dibo** [comment]
because the issue just happen when running the command `semantic-release` 
the mentioned [xsel](https://www.npmjs.com/package/xsel) doesn't have a repo, so we cannot report the issue there
