### ISSUE TITLE
npx semantic-release-cli setup

### ISSUE THREAD

**Issue by contact2praful** [semantic-release/cli#369]
While doing the setup of semantic getting below issue

> npx semantic-release-cli setup

? Is the GitHub repository private? Yes
? What is your npm registry? http://registry.npmjs.org/
? Which authentication method is this npm registry using? Legacy (username, password, email)
? What is your npm username? username
? What is your npm password? [hidden]
? What is your npm email address? sampleEmail@gmail.com
? Provide a GitHub Personal Access Token (create a token at https://github.com/settings/tokens/new?scopes=repo) TOKEN
? What CI are you using? Github Actions

ERR! semantic-release TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
ERR! semantic-release     at new NodeError (node:internal/errors:372:5)
ERR! semantic-release     at Function.from (node:buffer:323:9)
ERR! semantic-release     at createEncryptedSecret (/Users/XYZUSER/.npm/_npx/4b6729947d3d91fc/node_modules/semantic-release-cli/src/lib/github-actions.js:23:31)
ERR! semantic-release     at createSecret (/Users/XYZUSER/.npm/_npx/4b6729947d3d91fc/node_modules/semantic-release-cli/src/lib/github-actions.js:46:30)
ERR! semantic-release     at module.exports (/Users/XYZUSER/.npm/_npx/4b6729947d3d91fc/node_modules/semantic-release-cli/src/lib/github-actions.js:87:3)
ERR! semantic-release     at module.exports (/Users/XYZUSER/.npm/_npx/4b6729947d3d91fc/node_modules/semantic-release-cli/src/lib/ci.js:49:3)
ERR! semantic-release     at module.exports (/Users/XYZUSER/.npm/_npx/4b6729947d3d91fc/node_modules/semantic-release-cli/src/index.js:89:5)
ERR! semantic-release  TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
ERR! semantic-release     at new NodeError (node:internal/errors:372:5)
ERR! semantic-release     at Function.from (node:buffer:323:9)
ERR! semantic-release     at createEncryptedSecret (/Users/XYZUSER/.npm/_npx/4b6729947d3d91fc/node_modules/semantic-release-cli/src/lib/github-actions.js:23:31)
ERR! semantic-release     at createSecret (/Users/XYZUSER/.npm/_npx/4b6729947d3d91fc/node_modules/semantic-release-cli/src/lib/github-actions.js:46:30)
ERR! semantic-release     at module.exports (/Users/XYZUSER/.npm/_npx/4b6729947d3d91fc/node_modules/semantic-release-cli/src/lib/github-actions.js:87:3)
ERR! semantic-release     at module.exports (/Users/XYZUSER/.npm/_npx/4b6729947d3d91fc/node_modules/semantic-release-cli/src/lib/ci.js:49:3)
ERR! semantic-release     at module.exports (/Users/XYZUSER/.npm/_npx/4b6729947d3d91fc/node_modules/semantic-release-cli/src/index.js:89:5) {
ERR! semantic-release   code: 'ERR_INVALID_ARG_TYPE'
ERR! semantic-release }

**Comment by seebeen** [comment]
Operating system, node version, and are you pasting the entire token correctly?
