### ISSUE TITLE
ERR! semantic-release Could not create Travis CI hook.

### ISSUE THREAD

**Issue by gr2m** [semantic-release/cli#6]
```
? Is the GitHub repository private? No

? What is your npm registry? https://registry.npmjs.org/
? What is your npm username? gr2m
? What is your npm email? gregor@martynus.net
? What is your npm password? **************
? What is your GitHub username? gr2m
? What is your GitHub password? ************
? What CI are you using? Travis CI
ERR! semantic-release Could not create Travis CI hook.
ERR! semantic-release Error: Travis encountered an error, sorry :(
ERR! semantic-release     at /usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-ci.js:49:30
ERR! semantic-release     at Request._callback (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-http.js:49:13)
ERR! semantic-release     at Request.self.callback (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/index.js:148:22)
ERR! semantic-release     at Request.emit (events.js:98:17)
ERR! semantic-release     at Request.<anonymous> (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/index.js:886:14)
ERR! semantic-release     at Request.emit (events.js:117:20)
ERR! semantic-release     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/index.js:837:12)
ERR! semantic-release     at IncomingMessage.emit (events.js:117:20)
ERR! semantic-release     at _stream_readable.js:943:16
ERR! semantic-release     at process._tickCallback (node.js:419:13)
ERR! semantic-release  [Error: Travis encountered an error, sorry :(]
```

**Comment by boennemann** [comment]
@gr2m Use 1.0.3 and try again please :)

**Comment by gr2m** [comment]
same error

**Comment by boennemann** [comment]
@gr2m Can you verify that it works if you downgrade the CLI to 1.0.1?

**Comment by christophwitzko** [comment]
You might try to enable the repository on Travis manually https://travis-ci.org/profile

**Comment by gr2m** [comment]
the repository is already enabled: https://travis-ci.org/hoodiehq/pouchdb-hoodie-store

**Comment by gr2m** [comment]
sorry, same error on 1.0.1 :/

**Comment by gr2m** [comment]
worked fine on a new repo:
https://github.com/gr2m/tmp-test-repo

**Comment by boennemann** [comment]
@gr2m Try updating the metadata in the package.json: https://github.com/hoodiehq/pouchdb-hoodie-store/blob/master/package.json#L18

It seems like the cli is trying to enable this repo for hipsterbrown on travis.

**Comment by gr2m** [comment]
that was it :+1: 

Not sure if you can add a better error message, or make the setup more verbose if the provided github username isn't the one set in the git url?

**Comment by boennemann** [comment]
Good idea, we should dump the config it's using with the verbose loglevel. Glad it's working now!
