### ISSUE TITLE
Error running semantic-release setup with Node v5.4.0

### ISSUE THREAD

**Issue by uglow** [semantic-release/cli#76]
Semantic-release-cli version: 1.4.1
Node version: 5.4.0
Command:
```
npm i semantic-release-cli -g
semantic-release setup
```
Output:
```
Bretts-MBP:test-app brettuglow$ semantic-release-cli setup
module.js:423
  return process.dlopen(module, path._makeLong(filename));
                 ^
Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:423:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/mydev/tools/npm/lib/node_modules/semantic-release-cli/node_modules/keytar/lib/keytar.js:4:12)
    at Object.<anonymous> (/mydev/tools/npm/lib/node_modules/semantic-release-cli/node_modules/keytar/lib/keytar.js:58:4)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
Bretts-MBP:test-app brettuglow$ nvm use stable
Now using node v4.2.4
Bretts-MBP:test-app brettuglow$ semantic-release-cli setup
? Are you using GitHub Enterprise? (Y/n) 
```

Switching to Node v4.2.4 (4.x?) worked.

**Comment by uglow** [comment]
Closing issue - this could have a occurred due to switching between node versions and not running `npm rebuild -g`
