### ISSUE TITLE
Can't login to Github

### ISSUE THREAD

**Issue by alejandronanez** [semantic-release/cli#78]
Hello there, I'm having some issues while I try to use the package, I can't login into my Github account.

The last step I see in my terminal is "What is your Github username?" I hit enter and then I got this:

```
ERR! semantic-release Could not login to GitHub. Check your credentials.
ERR! semantic-release Error: Could not login to GitHub.
ERR! semantic-release     at Request._callback (/Users/alejandro/Code/projects/es6-project-boilerplate/node_modules/semantic-release-cli/dist/lib/github.js:72:8)
ERR! semantic-release     at Request.self.callback (/Users/alejandro/Code/projects/es6-project-boilerplate/node_modules/request/request.js:200:22)
ERR! semantic-release     at emitTwo (events.js:100:13)
ERR! semantic-release     at Request.emit (events.js:185:7)
ERR! semantic-release     at Request.<anonymous> (/Users/alejandro/Code/projects/es6-project-boilerplate/node_modules/request/request.js:1067:10)
ERR! semantic-release     at emitOne (events.js:95:20)
ERR! semantic-release     at Request.emit (events.js:182:7)
ERR! semantic-release     at IncomingMessage.<anonymous> (/Users/alejandro/Code/projects/es6-project-boilerplate/node_modules/request/request.js:988:12)
ERR! semantic-release     at emitNone (events.js:85:20)
ERR! semantic-release     at IncomingMessage.emit (events.js:179:7)
ERR! semantic-release  [Error: Could not login to GitHub.]
```

Node version: v5.5.0
NPM version: 3.8.0

Thanks!

**Comment by digitalsadhu** [comment]
I'm getting something like this with the latest updates.

```
? What is your npm registry? https://registry.npmjs.org/
? What is your npm username? digitalsadhu
ERR! semantic-release Error: Could not login to npm.
ERR! semantic-release     at getNpmToken (/usr/local/lib/node_modules/semantic-release-cli/src/lib/npm.js:51:21)
ERR! semantic-release     at <anonymous>
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:188:7)
ERR! semantic-release  { Error: Could not login to npm.
ERR! semantic-release     at getNpmToken (/usr/local/lib/node_modules/semantic-release-cli/src/lib/npm.js:51:21)
ERR! semantic-release     at <anonymous>
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:188:7)
ERR! semantic-release   stack: 'Error: Could not login to npm.\n    at getNpmToken (/usr/local/lib/node_modules/semantic-release-cli/src/lib/npm.js:51:21)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)' }
```
I reverted to 3.5.0 and all worked nicely
