### ISSUE TITLE
Could not install module with Node 6.2.0, NPM 3.9.3 (NVM v0.31.1) on Ubuntu 16.04

### ISSUE THREAD

**Issue by nmrony** [semantic-release/cli#81]
I am facing installation problem and my output looks like bellow
```sh
nmrony at dell-inspiron in ~
$ npm i semantic-release-cli -g --no-progress
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4
.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.3.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
/home/nmrony/.nvm/versions/node/v6.2.0/bin/semantic-release-cli -> /home/nmrony/.nvm/versions/node/v6.2.0/lib/node_modules/semantic-rele
ase-cli/bin/semantic-release.js

> keytar@3.0.2 install /home/nmrony/.nvm/versions/node/v6.2.0/lib/node_modules/semantic-release-cli/node_modules/keytar
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
Package gnome-keyring-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gnome-keyring-1.pc`
to the PKG_CONFIG_PATH environment variable
No package 'gnome-keyring-1' found
gyp: Call to 'pkg-config --libs-only-l gnome-keyring-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/nmrony/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/confi
gure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.4.0-22-generic
gyp ERR! command "/home/nmrony/.nvm/versions/node/v6.2.0/bin/node" "/home/nmrony/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_mod
ules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nmrony/.nvm/versions/node/v6.2.0/lib/node_modules/semantic-release-cli/node_modules/keytar
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
/home/nmrony/.nvm/versions/node/v6.2.0/lib
└── (empty)
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/home/nmrony/.nvm/versions/node/v6.2.0/bin/node" "/home/nmrony/.nvm/versions/node/v6.2.0/bin/npm" "i" "semantic-release-c
li" "-g"
npm ERR! node v6.2.0
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE

npm ERR! keytar@3.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@3.0.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs keytar
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nmrony/.nvm/npm-debug.log
npm ERR! code 1
```
I am using **Node v6.2.0**  and **NPM v3.9.3** installed via **NVM v0.30.1** on Ubuntu 16.04, I cleaned the cache but no luck. Please take a look into it.

**Comment by nmrony** [comment]
Hi @boennemann @christophwitzko Solved the issue by installing the following package from repository
```sh
sudo apt-get install libgnome-keyring-dev
```
Thanks

**Comment by bluewaitor** [comment]
:smiley:

**Comment by nmrony** [comment]
But I think you should list is as dependencies? @bluewaitor @boennemann

**Comment by PradeepJaiswar** [comment]
U just saved my life :)
