### ISSUE TITLE
Could not install module with Node 6.3.1, NPM 3.10.3 on Linux Mint 17.3

### ISSUE THREAD

**Issue by matheusml** [semantic-release/cli#86]
I'm having an installation issue. My output:

```
➜  ~ npm install -g semantic-release-cli --no-progress
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.3.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
/home/matheusml/.nvm/versions/node/v6.3.1/bin/semantic-release-cli -> /home/matheusml/.nvm/versions/node/v6.3.1/lib/node_modules/semantic-release-cli/bin/semantic-release.js

> keytar@3.0.2 install /home/matheusml/.nvm/versions/node/v6.3.1/lib/node_modules/semantic-release-cli/node_modules/keytar
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entrando no diretório `/home/matheusml/.nvm/versions/node/v6.3.1/lib/node_modules/semantic-release-cli/node_modules/keytar/build'
  CXX(target) Release/obj.target/keytar/src/main.o
make: g++: Comando não encontrado
make: ** [Release/obj.target/keytar/src/main.o] Erro 127
make: Saindo do diretório `/home/matheusml/.nvm/versions/node/v6.3.1/lib/node_modules/semantic-release-cli/node_modules/keytar/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/matheusml/.nvm/versions/node/v6.3.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.19.0-32-generic
gyp ERR! command "/home/matheusml/.nvm/versions/node/v6.3.1/bin/node" "/home/matheusml/.nvm/versions/node/v6.3.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/matheusml/.nvm/versions/node/v6.3.1/lib/node_modules/semantic-release-cli/node_modules/keytar
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
/home/matheusml/.nvm/versions/node/v6.3.1/lib
└── (empty)

npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/home/matheusml/.nvm/versions/node/v6.3.1/bin/node" "/home/matheusml/.nvm/versions/node/v6.3.1/bin/npm" "install" "-g" "semantic-release-cli" "--no-progress"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! keytar@3.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@3.0.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs keytar
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/matheusml/npm-debug.log
npm ERR! code 1
```

**Comment by Flame2057** [comment]
Same issue with latest NPM version on Windows 10.

**Comment by ocombe** [comment]
Same thing here with node 6.3.0 & windows 10 & npm 3.10.9 :(
