### ISSUE TITLE
Setup fails with "Could not get repository on Travis CI"

### ISSUE THREAD

**Issue by joeferraro** [semantic-release/cli#88]
```
ERR! semantic-release Could not get repository on Travis CI.
ERR! semantic-release { file: 'not found' }
```

My repo has been running thousands of Travis builds, is publicly available, etc. Any ideas?

**Comment by Flame2057** [comment]
I got the same issue.

**Comment by marvindanig** [comment]
Resounding the 'unable to locate the repo' issue! 

```
$  semantic-release-cli init
? Is the GitHub repository private? No
ERR! semantic-release Could not find repository on GitHub. Please create and add the repository.
ERR! semantic-release Error: GitHub repository not found.
ERR! semantic-release     at Request._callback (/Users/admin/.nvm/versions/node/v6.2.0/lib/node_modules/semantic-release-cli/dist/lib/repository.js:102:28)
ERR! semantic-release     at Request.self.callback (/Users/admin/.nvm/versions/node/v6.2.0/lib/node_modules/semantic-release-cli/node_modules/request/request.js:187:22)
ERR! semantic-release     at emitTwo (events.js:106:13)
ERR! semantic-release     at Request.emit (events.js:191:7)
ERR! semantic-release     at Request.<anonymous> (/Users/admin/.nvm/versions/node/v6.2.0/lib/node_modules/semantic-release-cli/node_modules/request/request.js:1044:10)
ERR! semantic-release     at emitOne (events.js:96:13)
ERR! semantic-release     at Request.emit (events.js:188:7)
ERR! semantic-release     at IncomingMessage.<anonymous> (/Users/admin/.nvm/versions/node/v6.2.0/lib/node_modules/semantic-release-cli/node_modules/request/request.js:965:12)
ERR! semantic-release     at emitNone (events.js:91:20)
ERR! semantic-release     at IncomingMessage.emit (events.js:185:7)
```

**Comment by crobinson42** [comment]
I'm getting this - the repo is under an organization that was setup on github. Any correlations?

**Comment by crobinson42** [comment]
re https://github.com/semantic-release/semantic-release/issues/156
