### ISSUE TITLE
ERR! Could not login to npm registry. Check your credentials.

### ISSUE THREAD

**Issue by finom** [semantic-release/cli#89]
Hey guys, getting weird error while trying to set up semantic-release. I have changed my password on NPM and successfully logged in again via ``npm login`` but the error is still there. What can I do to fix it? I even tried to remove .npmrc but it does not give any effect.
```
WARN semantic-release adduser Incorrect username or password
WARN semantic-release You can reset your account by visiting:
WARN semantic-release

WARN semantic-release     https://npmjs.org/forgot
WARN semantic-release
ERR! semantic-release Could not login to npm registry. Check your credentials.
ERR! semantic-release Error: Registry returned 401 for PUT on https://registry.npmjs.org/-/user/org.couchdb.user:finom
ERR! semantic-release     at RegClient.<anonymous> (/home/finom/.nvm/versions/node/v6.4.0/lib/node_modules/semantic-release-cli/node_modules/npm-r
egistry-client/lib/request.js:239:14)
ERR! semantic-release     at Request._callback (/home/finom/.nvm/versions/node/v6.4.0/lib/node_modules/semantic-release-cli/node_modules/npm-regis
try-client/lib/request.js:170:14)
ERR! semantic-release     at Request.self.callback (/home/finom/.nvm/versions/node/v6.4.0/lib/node_modules/semantic-release-cli/node_modules/reque
st/request.js:187:22)
ERR! semantic-release     at emitTwo (events.js:106:13)
ERR! semantic-release     at Request.emit (events.js:191:7)
ERR! semantic-release     at Request.<anonymous> (/home/finom/.nvm/versions/node/v6.4.0/lib/node_modules/semantic-release-cli/node_modules/request
/request.js:1044:10)
ERR! semantic-release     at emitOne (events.js:96:13)
ERR! semantic-release     at Request.emit (events.js:188:7)
ERR! semantic-release     at IncomingMessage.<anonymous> (/home/finom/.nvm/versions/node/v6.4.0/lib/node_modules/semantic-release-cli/node_modules
/request/request.js:965:12)
ERR! semantic-release     at emitNone (events.js:91:20)
ERR! semantic-release  { Error: Registry returned 401 for PUT on https://registry.npmjs.org/-/user/org.couchdb.user:finom
ERR! semantic-release     at RegClient.<anonymous> (/home/finom/.nvm/versions/node/v6.4.0/lib/node_modules/semantic-release-cli/node_modules/npm-r
egistry-client/lib/request.js:239:14)
ERR! semantic-release     at Request._callback (/home/finom/.nvm/versions/node/v6.4.0/lib/node_modules/semantic-release-cli/node_modules/npm-regis
try-client/lib/request.js:170:14)
ERR! semantic-release     at Request.self.callback (/home/finom/.nvm/versions/node/v6.4.0/lib/node_modules/semantic-release-cli/node_modules/reque
st/request.js:187:22)
ERR! semantic-release     at emitTwo (events.js:106:13)
ERR! semantic-release     at Request.emit (events.js:191:7)
ERR! semantic-release     at Request.<anonymous> (/home/finom/.nvm/versions/node/v6.4.0/lib/node_modules/semantic-release-cli/node_modules/request
/request.js:1044:10)
ERR! semantic-release     at emitOne (events.js:96:13)
ERR! semantic-release     at Request.emit (events.js:188:7)
ERR! semantic-release     at IncomingMessage.<anonymous> (/home/finom/.nvm/versions/node/v6.4.0/lib/node_modules/semantic-release-cli/node_modules
/request/request.js:965:12)
ERR! semantic-release     at emitNone (events.js:91:20) statusCode: 401, code: 'E401' }

```

I use npm 3.10.3 and node 6.4.0 via nvm.

**Comment by finom** [comment]
Just found ``--ask-for-passwords`` flag which fixed my issue.

**Comment by jedwards1211** [comment]
This should be reopened, even after successfully running `npm login` I can't get this to work without passwords, and I don't know why.

**Comment by priestine** [comment]
@finom suggestion actually works. The problem is somewhat related to keytar being not installed correctly. At least, this is what the terminal says :rofl:
